services:

  postgres:
    image: postgres:16
    container_name: smartims-postgres

    restart: always

    environment:
      POSTGRES_DB: smart_ims
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: smartims-backend

    depends_on:
      - postgres

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/smart_ims
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: smartims-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres-data: