apiVersion: v1
kind: Secret
metadata:
  name: smartims-secret
  namespace: smartims

type: Opaque

stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "ThisIsASecretKeyForJwtSigningMustBeAtLeast32Chars"
